eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/tidb-cluster/bin

if [ -d "/mirrors" ]; then
	export tidb_MIRRORS=/mirrors
fi

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

cat <<EOF
Welcome to tidb-cluster-control on Docker
===========================

This container runs the tidb-cluster tests in sub-containers.

You are currently in the base dir of the git repo for tidb-cluster.

Run the following in your terminal, and follow the instructions:

curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh 

EOF

