eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

export PATH=$PATH:/usr/local/go/bin
export PATH=/root/.tiup/bin:$PATH

if [ -d "/mirrors" ]; then
	export tidb_MIRRORS=/mirrors
fi

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

cat <<EOF
Welcome to tidb-cluster-control on Docker
===========================

This container runs the tidb-cluster tests in sub-containers.

You are currently in the base dir of the git repo for tidb-cluster.

try: 

tiup cluster deploy demo v4.0.0-rc topology.yml


EOF

